name : Graphics | Distributed | Simulation 
description : A Technical Blog
footer-links:
  github: harmoli
  twitter: harmo_li
  email: harmoli@seas.upenn.edu
url: http://blog.harmonymli.com
baseurl: "/"
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title.html
author: Harmony M Li
authorurl: http://www.harmonymli.com
exclude: [ "Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'CNAME' ]
paginate: 5
